### ISSUE TITLE
Uncaught Uncaught Uncaught Uncaught Uncaught Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by Axure** [rogerpadilla/angular2-minimalist-starter#10]
A series of errors arise when I access the index:
>Uncaught SyntaxError: Unexpected token <
(program):1 Uncaught SyntaxError: Unexpected token <
system.js:4 Uncaught Uncaught SyntaxError: Unexpected token <
	Evaluating http://localhost:8080/@reactivex/rxjs/dist/cjs/Subject.js
system.js:4 Uncaught Uncaught Uncaught SyntaxError: Unexpected token <
	Evaluating http://localhost:8080/@reactivex/rxjs/dist/cjs/Subject.js
	Evaluating http://localhost:8080/lib/angular2/src/core/facade/async.js
system.js:4 Uncaught Uncaught Uncaught Uncaught SyntaxError: Unexpected token <
	Evaluating http://localhost:8080/@reactivex/rxjs/dist/cjs/Subject.js
	Evaluating http://localhost:8080/lib/angular2/src/core/facade/async.js
	Evaluating http://localhost:8080/lib/angular2/src/core/pipes/async_pipe.js
system.js:4 Uncaught Uncaught Uncaught Uncaught Uncaught SyntaxError: Unexpected token <
	Evaluating http://localhost:8080/@reactivex/rxjs/dist/cjs/Subject.js
	Evaluating http://localhost:8080/lib/angular2/src/core/facade/async.js
	Evaluating http://localhost:8080/lib/angular2/src/core/pipes/async_pipe.js
	Evaluating http://localhost:8080/lib/angular2/src/core/pipes.js
system.js:4 Uncaught Uncaught Uncaught Uncaught Uncaught Uncaught SyntaxError: Unexpected token <
	Evaluating http://localhost:8080/@reactivex/rxjs/dist/cjs/Subject.js
	Evaluating http://localhost:8080/lib/angular2/src/core/facade/async.js
	Evaluating http://localhost:8080/lib/angular2/src/core/pipes/async_pipe.js
	Evaluating http://localhost:8080/lib/angular2/src/core/pipes.js
	Evaluating http://localhost:8080/lib/angular2/core.js
system.js:4 Uncaught Uncaught Uncaught Uncaught Uncaught Uncaught Uncaught SyntaxError: Unexpected token <
	Evaluating http://localhost:8080/@reactivex/rxjs/dist/cjs/Subject.js
	Evaluating http://localhost:8080/lib/angular2/src/core/facade/async.js
	Evaluating http://localhost:8080/lib/angular2/src/core/pipes/async_pipe.js
	Evaluating http://localhost:8080/lib/angular2/src/core/pipes.js
	Evaluating http://localhost:8080/lib/angular2/core.js
	Evaluating http://localhost:8080/lib/angular2/angular2.js
zone.js:115 Uncaught Uncaught Uncaught Uncaught Uncaught Uncaught Uncaught SyntaxError: Unexpected token <
	Evaluating http://localhost:8080/@reactivex/rxjs/dist/cjs/Subject.js
	Evaluating http://localhost:8080/lib/angular2/src/core/facade/async.js
	Evaluating http://localhost:8080/lib/angular2/src/core/pipes/async_pipe.js
	Evaluating http://localhost:8080/lib/angular2/src/core/pipes.js
	Evaluating http://localhost:8080/lib/angular2/core.js
	Evaluating http://localhost:8080/lib/angular2/angular2.js
	Evaluating http://localhost:8080/client/bootstrap.js
	Error loading http://localhost:8080/client/bootstrap.js

Also when I run npm start, some errors occurred when executing `gulp ts`:
>C:/Users/lluvi/Desktop/angular2-minimalist-starter/typings/angular2/angular2.d.ts(1806,74): error TS2304: Cannot find name 'ParameterDecorator'.
C:/Users/lluvi/Desktop/angular2-minimalist-starter/typings/angular2/angular2.d.ts(7652,74): error TS2304: Cannot find name 'ParameterDecorator'.
C:/Users/lluvi/Desktop/angular2-minimalist-starter/typings/angular2/router.d.ts(567,9): error TS2304: Cannot find name 'ClassDecorator'.
C:/Users/lluvi/Desktop/angular2-minimalist-starter/typings/angular2/router.d.ts(721,53): error TS2304: Cannot find name 'ClassDecorator'.
[03:41:21] TypeScript: 4 semantic errors
[03:41:21] TypeScript: emit succeeded (with errors)
[03:41:21] Finished 'ts' after 3.55 s

**Comment by flyingzl** [comment]
@Axure  Since angular2 have been upgrade to alpha 40 now, the examples are out of date now..please visit my [project](https://github.com/flyingzl/angular2-seed).

**Comment by rogerpadilla** [comment]
Please try again, upgraded to alpha 44, added tests, and several improvenments.
