### ISSUE TITLE
Contact update not shown

### ISSUE THREAD

**Issue by frankbenoit** [rogerpadilla/angular2-minimalist-starter#13]
Hi

when clicking on an item in the list, modify it, press "update", the change is not shown in the list.
A page reload is needed.

Frank

**Comment by frankbenoit** [comment]
The problem is when resetting the form.
https://github.com/angular/angular/issues/6005

A solution, that works for me is, when the 'contact' reference is removed from the html. Instead the components creates for all controls (from the ControlGroup) member fields and sets/updates the values over them.

Member fields ...

    ctrl_id: Control = new Control('');
    ctrlName: Control = new Control('', Validators.required);
    ctrlEmail: Control = new Control('', validateEmail);

in saveOne:

    this.contact = {
        _id : this.ctrl_id.value,
        name : this.ctrlName.value,
        email : this.ctrlEmail.value
     };

and resetFrom:

    resetForm(data: Contact = {}) {
        this.contact = data;
        this.ctrl_id.updateValue( data._id );
        this.ctrlName.updateValue( data.name );
        this.ctrlEmail.updateValue( data.email );
    }

I don't know if this is the right way. 
If you like i can create a pull request.

**Comment by rogerpadilla** [comment]
Hi, thanks. I added some custom CSS for visual feedback instead of using form-control's properties (there occurred some breaking changes in the last Angular's upgrade).

You can details of the change here: https://github.com/rogerpadilla/angular2-minimalist-starter/commit/bb4924c972014aa67cfbb2018a23b31c56dba971
