### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by Marco-exports** [rogerpadilla/angular2-minimalist-starter#16]
Hi Roger,

Your work inspired me to build a MongoDB/Mongoose generic service for my apps, which works nicely for any collection (table).  I convert a Mongoose "model" into an A2 "interface", parsing out needed parts, which your http services can handle...

I tried to delete one document (record), and Express deletes in MongoDB and replies with "204"...

But, I get **SyntaxError: Unexpected end of input** in Chrome. 

I found a similar error generated in AngularJS:

https://github.com/angular/angular.js/issues/9532

Wondering if there is a way to get around this, or if it needs fixing inside A2 ?

Thanks !

**Comment by Marco-exports** [comment]
Quick note...  
In Express I send a reply on Delete with **200**:

`return res.status(200).send('{"result" : "OK"}')`

... and the problem goes away.

HTTP rules say that **204** never gets a body reply, which is what breaks in A2.

**Comment by rogerpadilla** [comment]
Hi Marco,

200 is the default http code for responses so you can omit that. And a
string is not a valid JSON, just pass the JavaScript object and express
will serielizes that for you.

return res.send({result: "OK"});
